### ISSUE TITLE
Eiso's blog post about 100 awesome women's image is not cool

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/landing#186] opened 2017-10-17 08:18 UTC
![image](https://user-images.githubusercontent.com/2793551/31653895-76311bae-b324-11e7-9464-dedcf3e5af24.png)

Darkish background, pale logo

**Comment by marnovo** [comment] 2017-10-20 17:53
This is according to the original design. Plus, you can just PR a cool picture for it. ;)
P.s.: it will vanish this week once we post the launch post and the brand persona/design guide one.

**Comment by dpordomingo** [comment] 2017-11-02 19:10
Since it was designed that way, I'd close this issue till we have a new design, or a PR proposing a new default image.
Feel free to reopen if needed.

**Closed by dpordomingo** 2017-11-02 19:10 UTC
